#import "macos_clipboard.h"
#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>
#include <stdlib.h>
#include <string.h>

// Pasteboard marker MaccyZig stamps on its own writes so the polling timer
// can ignore them. Kept distinct from the upstream Maccy marker to give us a
// stable identity tied to our own bundle id.
static NSString *const kMZMaccyMarkerType = @"io.github.chang1o1.MaccyZig";
static NSString *const kMZUpstreamMaccyMarkerType = @"org.p0deje.Maccy";
static NSString *const kMZSourceMarkerType = @"org.nspasteboard.source";
static NSString *const kMZAutoGeneratedType = @"org.nspasteboard.AutoGeneratedType";
static NSString *const kMZConcealedType = @"org.nspasteboard.ConcealedType";
static NSString *const kMZTransientType = @"org.nspasteboard.TransientType";
static NSString *const kMZModifiedType = @"x.nspasteboard.ModifiedType";
static NSString *const kMZDynamicTypePrefix = @"dyn.";
static NSString *const kMZMicrosoftSourcePrefix = @"com.microsoft.ole.source.";

static char *mz_strdup_ns(NSString *value) {
  if (value == nil) return NULL;
  const char *utf8 = [value UTF8String];
  if (utf8 == NULL) return NULL;
  size_t n = strlen(utf8);
  char *out = (char *)malloc(n + 1);
  if (out == NULL) return NULL;
  memcpy(out, utf8, n + 1);
  return out;
}

static int mz_type_enabled(NSString *type, NSSet<NSString *> *enabled) {
  return [enabled containsObject:type] ? 1 : 0;
}

static int mz_type_is_marker(NSString *type) {
  if (type == nil) return 0;
  return [type isEqualToString:kMZMaccyMarkerType] ||
         [type isEqualToString:kMZUpstreamMaccyMarkerType] ||
         [type isEqualToString:kMZSourceMarkerType];
}

static int mz_type_is_transient(NSString *type) {
  if (type == nil) return 0;
  return [type isEqualToString:kMZAutoGeneratedType] ||
         [type isEqualToString:kMZConcealedType] ||
         [type isEqualToString:kMZTransientType] ||
         [type isEqualToString:kMZModifiedType] ||
         [type hasPrefix:kMZDynamicTypePrefix] ||
         [type hasPrefix:kMZMicrosoftSourcePrefix];
}

static int mz_type_is_string_backed(NSString *type) {
  if (type == nil) return 0;
  return [type isEqualToString:@"public.utf8-plain-text"] ||
         [type isEqualToString:@"public.text"] ||
         [type isEqualToString:@"public.url"] ||
         [type isEqualToString:@"public.file-url"] ||
         [type isEqualToString:@"public.url-name"];
}

static int mz_append_blob(MZSnapshot *snapshot, NSString *type, NSData *data) {
  if (type == nil || data == nil) return 0;
  char *type_copy = mz_strdup_ns(type);
  if (type_copy == NULL) return -1;

  size_t len = [data length];
  uint8_t *data_copy = NULL;
  if (len > 0) {
    data_copy = (uint8_t *)malloc(len);
    if (data_copy == NULL) {
      free(type_copy);
      return -1;
    }
    memcpy(data_copy, [data bytes], len);
  }

  size_t next_count = snapshot->count + 1;
  MZBlob *new_blobs = (MZBlob *)realloc(snapshot->blobs, next_count * sizeof(MZBlob));
  if (new_blobs == NULL) {
    free(type_copy);
    if (data_copy != NULL) free(data_copy);
    return -1;
  }
  snapshot->blobs = new_blobs;

  MZBlob *blob = &snapshot->blobs[snapshot->count];
  blob->type = type_copy;
  blob->len = len;
  blob->data = data_copy;
  snapshot->count = next_count;
  return 0;
}

int mz_clipboard_snapshot(MZSnapshot *out,
                          const char **enabled_types,
                          size_t enabled_count,
                          size_t max_blob_bytes) {
  if (out == NULL) return -1;
  memset(out, 0, sizeof(MZSnapshot));

  @autoreleasepool {
    NSMutableSet<NSString *> *enabled = [NSMutableSet setWithCapacity:enabled_count];
    for (size_t i = 0; i < enabled_count; i++) {
      if (enabled_types[i] != NULL) {
        [enabled addObject:[NSString stringWithUTF8String:enabled_types[i]]];
      }
    }

    NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
    out->change_count = [pasteboard changeCount];

    NSRunningApplication *frontmost = [[NSWorkspace sharedWorkspace] frontmostApplication];
    out->source_bundle = mz_strdup_ns([frontmost bundleIdentifier]);

    NSArray<NSPasteboardItem *> *items = [pasteboard pasteboardItems];
    for (NSPasteboardItem *item in items) {
      for (NSPasteboardType type in [item types]) {
        NSString *type_string = (NSString *)type;
        if ([type_string isEqualToString:kMZMaccyMarkerType] ||
            [type_string isEqualToString:kMZUpstreamMaccyMarkerType]) {
          // Either marker means "a Maccy-family app already wrote this", so we
          // should not re-capture it. The upstream id covers two cases at once:
          // legacy v0.0.2 writes already on the pasteboard during upgrade, and
          // a coexisting upstream Maccy install.
          out->has_maccy_marker = 1;
          continue;
        }
        if (mz_type_is_marker(type_string)) continue;
        if (mz_type_is_transient(type_string)) {
          out->skipped_transient_count += 1;
          continue;
        }
        if (!mz_type_enabled(type_string, enabled)) {
          out->skipped_type_count += 1;
          continue;
        }
        NSData *data = [item dataForType:type];
        if (data == nil) {
          out->skipped_transient_count += 1;
          continue;
        }
        if (max_blob_bytes > 0 && [data length] > max_blob_bytes) {
          out->skipped_oversize_count += 1;
          continue;
        }
        if (mz_append_blob(out, type_string, data) != 0) {
          mz_clipboard_snapshot_free(out);
          return -1;
        }
      }
    }
  }

  return 0;
}

int64_t mz_clipboard_change_count(void) {
  @autoreleasepool {
    return [[NSPasteboard generalPasteboard] changeCount];
  }
}

void mz_clipboard_snapshot_free(MZSnapshot *snapshot) {
  if (snapshot == NULL) return;
  if (snapshot->source_bundle != NULL) free(snapshot->source_bundle);
  for (size_t i = 0; i < snapshot->count; i++) {
    if (snapshot->blobs[i].type != NULL) free(snapshot->blobs[i].type);
    if (snapshot->blobs[i].data != NULL) free(snapshot->blobs[i].data);
  }
  if (snapshot->blobs != NULL) free(snapshot->blobs);
  memset(snapshot, 0, sizeof(MZSnapshot));
}


int mz_clipboard_write(const MZBlob *blobs, size_t count, const char *source_bundle) {
  if (blobs == NULL && count > 0) return -1;
  @autoreleasepool {
    NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];
    [pasteboard clearContents];
    NSMutableArray<NSString *> *types = [NSMutableArray arrayWithCapacity:count + 2];
    for (size_t i = 0; i < count; i++) {
      if (blobs[i].type == NULL || blobs[i].data == NULL) continue;
      [types addObject:[NSString stringWithUTF8String:blobs[i].type]];
    }
    [types addObject:kMZMaccyMarkerType];
    [types addObject:kMZSourceMarkerType];
    [pasteboard declareTypes:types owner:nil];
    for (size_t i = 0; i < count; i++) {
      if (blobs[i].type == NULL || blobs[i].data == NULL) continue;
      NSString *type = [NSString stringWithUTF8String:blobs[i].type];
      NSData *data = [NSData dataWithBytes:blobs[i].data length:blobs[i].len];
      if (mz_type_is_string_backed(type)) {
        NSString *string = [[NSString alloc] initWithBytes:blobs[i].data
                                                    length:blobs[i].len
                                                  encoding:NSUTF8StringEncoding];
        if (string != nil) {
          [pasteboard setString:string forType:type];
          continue;
        }
      }
      [pasteboard setData:data forType:type];
    }
    [pasteboard setString:@"" forType:kMZMaccyMarkerType];
    if (source_bundle != NULL) {
      [pasteboard setString:[NSString stringWithUTF8String:source_bundle] forType:kMZSourceMarkerType];
    }
  }
  return 0;
}
